apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSzh1aGJTNUdjT2t3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeU1EUXlNVEEzTWpGYUZ3MHpOVEV5TURJeU1URXlNakZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMrbThtSjdTZm5lUDVUeWorak1zOS9BUlBOQ0lqWkoyNFdrUWxSb0Z3eU0wZzZGVWJoY2xOUHRKeEYKSzFWOEJMR1J5NXJvODVQYTVyeVV1ZGpkV05zTVZrT2VTNkhpM3VWblZobHJJUjBZUm9zSEJ2UXpmck9nRklsNwpvK1pSRitIQURJY1NxWThoaHo4M0ZoeEFLTk9yTzlnbmNhN2NLT2Nzd3YxWVdyVDZ2cmp4U0RKckl0SFJZcEhHCnRhdVI5cXJ3V0dBdW1ZTTdKRys0MXVEZENGd0I4eHpYU1pLTmlDVDlzc3hpRFhlcTYzMDg1ZG9GekRkaHNNSUcKampCSkMrRXVRcDNoT2s5cnRDLzEzTDEwTVYrU0Q4NVZhbUcvbkRlN3JsWTBIOEV3eHNFR2p6aWlNdU9BeVVFVQpNZ2pEUGYwNE1Lc3hCaitjeGJyU21tUzlEMmk1QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTYm44anFFRzdWMHMyNFIweHc3b3d1aXV3L2ZEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWNVdmt1T2puMAoyb2dKazNlZllyVjNXQzQzdnhWM0RzYlJ3RDF2K1Z4ZHFLdXlKQnBnUGdTZDdTNURpZlE4VW5XS2hQUFBzNDZzCkVFSlZmdzJQa3dSVjBHbEVKZlVncWwrZ2t2K1N1czI3NG9VN1FLT1FNZWNYU0M0VVNSR2MvSzRtZW9aZCt3aE4KbjV1R3ZhQW9mOEtxNWNuUllEczJHRGNXUzJMcmpGRnMrcW5aeXUwMU1UaGp2ZTNmMk9FODF3TWVRN0xpb0IrOQoydk1MaHk1cG1Wc2RGQVlwd3hGQnhVYlN4b0tzMkRHaXNhaTdFVXRtaTlBeS94QXZWSjQ5Yk0reitudkFZd3l6CkVxU1VVcXJ0eDA5WjdaZTY5ZUt0NkdwVURRY1I1Q0wyRXI3ZXBEckNxNjd2SUh5OVZiWXRtd1JHaTVndUV5aGwKT1dhMmtLZ2Jab2VXCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://36ADB73A547AAC3E0D71E857C95CE822.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:872515281253:cluster/sam-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:872515281253:cluster/sam-cluster
    user: arn:aws:eks:us-east-1:872515281253:cluster/sam-cluster
  name: arn:aws:eks:us-east-1:872515281253:cluster/sam-cluster
current-context: arn:aws:eks:us-east-1:872515281253:cluster/sam-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:872515281253:cluster/sam-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - sam-cluster
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
